jobs:
- job: linux
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq software-properties-common
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
      sudo apt-get install -qq autoconf automake gcc g++ make
    displayName: Install common
  - script: |
      ./autogen.sh
      ./configure
      make
    displayName: Compiling ntCard
  - script: |
      make check
    displayName: Integration test
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-7
      sudo ln -s clang-format-7 /usr/bin/clang-format
  - script: make clang-format
    displayName: Run clang-format
